_wandb:
    value:
        cli_version: 0.28.1
        e:
            rv3fcipewjp4agb7egftnolkdgeidiq6:
                args:
                    - tests/test_vla_baselines.py
                    - -v
                cpu_count: 20
                cpu_count_logical: 20
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "4031871553536"
                        used: "2077202497536"
                email: gyanateet@gmail.com
                executable: /home/aimsgroupuol/miniconda3/envs/mpc_vla/bin/python3.11
                gpu: NVIDIA GB10
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 6144
                      name: NVIDIA GB10
                      uuid: GPU-495c5b99-32b7-2405-921e-d973a6bdb138
                host: spark-1240
                memory:
                    total: "130663591936"
                os: Linux-6.17.0-1014-nvidia-aarch64-with-glibc2.39
                program: /home/aimsgroupuol/miniconda3/envs/mpc_vla/bin/pytest
                python: CPython 3.11.15
                root: /home/aimsgroupuol/AIMSgeneral/Gyanateet/mpc_vla_diffusion_study
                startedAt: "2026-08-11T17:46:58.573579Z"
                writerId: rv3fcipewjp4agb7egftnolkdgeidiq6
        m: []
        python_version: 3.11.15
        t:
            "1":
                - 1
                - 11
                - 49
                - 71
            "2":
                - 1
                - 11
                - 49
                - 71
            "3":
                - 16
                - 61
            "4": 3.11.15
            "5": 0.28.1
            "6": 5.15.0
            "10":
                - 20
            "12": 0.28.1
            "13": linux-aarch64
